server:
  port: 8888
  ssl:
    enabled: true
    client-auth: need
    key-store: '/certificates/config-server-keystr.p12'
    key-store-password: password
    key-store-type: PKCS12
    trust-store: '/certificates/config-server-truststr.p12'
    trust-store-password: password
    trust-store-type: PKCS12
spring:
  cloud:
    config:
      server:
        git:
          uri: 'git@github.com:iaukhim/config-server-sources.git'
  security:
    basic:
      enable: true
    user:
      name: 'admin'
      password: 'admin'
encrypt:
  keyStore:
    location: file:/certificates/config-server.jks
    password: 123456
    alias: config-server-key
    secret: 123456
management:
  server:
    port: 8989
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health